# Large/Challenging configuration for final experiments
# Larger grid, longer training, for best results

environment:
  grid_size: 16
  max_steps: null
  step_penalty: -0.01
  death_penalty: -1.0
  food_reward: 1.0
  distance_reward_scale: 0.0
  frame_stack: 1

ppo:
  learning_rate: 0.0003
  n_steps: 512
  batch_size: 1024
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: null

training:
  total_timesteps: 5000000  # 5M timesteps for thorough training
  eval_freq: 25000
  save_freq: 100000

notes: |
  Large, challenging configuration for final results.
  16x16 grid requires more sophisticated behavior.
  Requires GPU for reasonable training time.
  Expect several hours of training on modern GPU.