# Small/Fast configuration for quick experiments and debugging
# Smaller grid, fewer timesteps, good for testing

environment:
  grid_size: 8
  max_steps: null
  step_penalty: -0.01
  death_penalty: -1.0
  food_reward: 1.0
  distance_reward_scale: 0.0
  frame_stack: 1

policy: CnnPolicy

ppo:
  learning_rate: 0.0003
  n_steps: 128
  batch_size: 256
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: null
  policy_kwargs:
    normalize_images: false  # Our env outputs float32 [0,1], already normalized

training:
  total_timesteps: 200000  # Quick training for testing
  eval_freq: 5000
  save_freq: 25000

notes: |
  Smaller, faster configuration for quick experiments.
  8x8 grid is easier to learn but less challenging.
  Use for debugging and rapid iteration.