# Ablation: Frame stacking
# Tests impact of temporal context via frame stacking

environment:
  grid_size: 12
  max_steps: null
  step_penalty: -0.01
  death_penalty: -1.0
  food_reward: 1.0
  distance_reward_scale: 0.0
  frame_stack: 4  # Stack last 4 frames

policy: CnnPolicy

ppo:
  learning_rate: 0.0003
  n_steps: 256
  batch_size: 512
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: null
  policy_kwargs:
    normalize_images: false

training:
  total_timesteps: 500000
  eval_freq: 10000
  save_freq: 50000

notes: |
  Ablation study: Frame stacking (4 frames).
  Hypothesis: Temporal context helps agent infer direction/velocity.
  Compare with base.yaml (frame_stack=1).
  Note: Increases observation size from (3,12,12) to (12,12,12).