# Ablation: Distance-based reward shaping
# Tests impact of adding distance-to-food reward signal

environment:
  grid_size: 12
  max_steps: null
  step_penalty: -0.01
  death_penalty: -1.0
  food_reward: 1.0
  distance_reward_scale: 0.01  # Enable distance shaping
  frame_stack: 1

ppo:
  learning_rate: 0.0003
  n_steps: 256
  batch_size: 512
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: null

training:
  total_timesteps: 500000
  eval_freq: 10000
  save_freq: 50000

notes: |
  Ablation study: Distance-based reward shaping.
  Hypothesis: Providing gradient towards food accelerates learning.
  Compare with base.yaml (distance_reward_scale=0.0).